import { describe, expect, it, beforeEach, afterEach } from 'vitest';
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { loadRules, parseRuleFile, selectActiveRules, synthesizeRule } from './rules.js';

const TEST_DIR = resolve('/tmp', 'mochi-rules-test-' + Math.random().toString(36).slice(2, 8));

describe('Rules System', () => {
  beforeEach(() => {
    mkdirSync(TEST_DIR, { recursive: true });
  });

  afterEach(() => {
    rmSync(TEST_DIR, { recursive: true, force: true });
  });

  it('parses markdown rule files with and without YAML frontmatter', () => {
    const withFm = resolve(TEST_DIR, 'ts-rules.md');
    writeFileSync(
      withFm,
      `---
title: "TypeScript ESM Rules"
globs: ["*.ts", "*.tsx"]
keywords: ["import", "esm"]
autoGenerated: false
---

Always use .js extension in relative imports.
`
    );

    const parsed = parseRuleFile(withFm);
    expect(parsed).not.toBeNull();
    expect(parsed?.title).toBe('TypeScript ESM Rules');
    expect(parsed?.globs).toEqual(['*.ts', '*.tsx']);
    expect(parsed?.keywords).toEqual(['import', 'esm']);
    expect(parsed?.content).toContain('Always use .js extension');

    const plain = resolve(TEST_DIR, 'plain.md');
    writeFileSync(plain, '# General Style\n\nKeep functions small and pure.');
    const plainParsed = parseRuleFile(plain);
    expect(plainParsed?.title).toBe('General Style');
    expect(plainParsed?.content).toContain('Keep functions small');
  });

  it('loads all rules from .mochi/rules/ directory', () => {
    synthesizeRule(
      TEST_DIR,
      'test-rule',
      'Test Rule Title',
      'Run unit tests before committing.',
      { keywords: ['test', 'vitest'] }
    );

    const loaded = loadRules(TEST_DIR);
    expect(loaded.length).toBe(1);
    expect(loaded[0].id).toBe('test-rule');
    expect(loaded[0].title).toBe('Test Rule Title');
    expect(loaded[0].keywords).toEqual(['test', 'vitest']);
    expect(loaded[0].autoGenerated).toBe(true);
  });

  it('selects active rules based on modified files and prompt keywords', () => {
    const rules = [
      {
        id: 'r1',
        title: 'TS Rule',
        globs: ['*.ts'],
        content: 'TS only',
        source: 'r1.md',
      },
      {
        id: 'r2',
        title: 'Python Rule',
        globs: ['*.py'],
        content: 'Python only',
        source: 'r2.md',
      },
      {
        id: 'r3',
        title: 'Database Rule',
        keywords: ['sql', 'database', 'migration'],
        content: 'DB only',
        source: 'r3.md',
      },
      {
        id: 'r4',
        title: 'Universal Rule',
        content: 'Applies everywhere',
        source: 'r4.md',
      },
    ];

    const activeForTs = selectActiveRules(rules, ['src/index.ts'], 'Fix bug');
    expect(activeForTs.map((r) => r.id)).toEqual(['r1', 'r4']);

    const activeForDb = selectActiveRules(rules, [], 'Write a SQL migration for users');
    expect(activeForDb.map((r) => r.id)).toEqual(['r3', 'r4']);
  });

  it('auto-discovers rules from .cursor/rules, .claude/rules, .cursorrules, and .github/copilot-instructions.md', () => {
    // 1. .cursor/rules/
    const cursorRulesDir = resolve(TEST_DIR, '.cursor', 'rules');
    mkdirSync(cursorRulesDir, { recursive: true });
    writeFileSync(resolve(cursorRulesDir, 'react.mdc'), '---\ndescription: React best practices\nglobs: ["*.tsx"]\n---\nUse functional components.');

    // 2. .claude/rules/
    const claudeRulesDir = resolve(TEST_DIR, '.claude', 'rules');
    mkdirSync(claudeRulesDir, { recursive: true });
    writeFileSync(resolve(claudeRulesDir, 'testing.md'), '# Testing Guidelines\nAlways write unit tests.');

    // 3. .cursorrules
    writeFileSync(resolve(TEST_DIR, '.cursorrules'), '# Project Rule\nKeep dependencies minimal.');

    // 4. .github/copilot-instructions.md
    const githubDir = resolve(TEST_DIR, '.github');
    mkdirSync(githubDir, { recursive: true });
    writeFileSync(resolve(githubDir, 'copilot-instructions.md'), '# Copilot Rule\nFollow style guide.');

    const rules = loadRules(TEST_DIR);
    expect(rules.length).toBe(4);
    const titles = rules.map((r) => r.title);
    expect(titles).toContain('React best practices');
    expect(titles).toContain('Testing Guidelines');
    expect(titles).toContain('Project Rule');
    expect(titles).toContain('Copilot Rule');
  });
});
