import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

export interface ProjectRule {
  id: string;
  title: string;
  globs?: string[];
  keywords?: string[];
  content: string;
  source: string;
  autoGenerated?: boolean;
}

/** Parse frontmatter or header from markdown rule files */
export function parseRuleFile(filePath: string): ProjectRule | null {
  if (!existsSync(filePath)) return null;
  try {
    const raw = readFileSync(filePath, 'utf8');
    const id = filePath.split('/').pop()?.replace(/\.md$/, '') ?? 'rule';
    let content = raw;
    let title = id;
    let globs: string[] | undefined;
    let keywords: string[] | undefined;
    let autoGenerated = false;

    // Check for YAML-like frontmatter: --- ... ---
    const fmMatch = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
    if (fmMatch) {
      const fm = fmMatch[1];
      content = fmMatch[2].trim();
      for (const line of fm.split('\n')) {
        const [k, ...vParts] = line.split(':');
        if (!k || vParts.length === 0) continue;
        const v = vParts.join(':').trim();
        const key = k.trim();
        if (key === 'title') title = v.replace(/^['"]|['"]$/g, '');
        if (key === 'globs') {
          try {
            globs = JSON.parse(v);
          } catch {
            globs = v.split(',').map((s) => s.trim().replace(/^['"\[]|['"\]]$/g, '')).filter(Boolean);
          }
        }
        if (key === 'keywords') {
          try {
            keywords = JSON.parse(v);
          } catch {
            keywords = v.split(',').map((s) => s.trim().replace(/^['"\[]|['"\]]$/g, '')).filter(Boolean);
          }
        }
        if (key === 'autoGenerated') autoGenerated = v.toLowerCase() === 'true';
      }
    } else {
      const h1 = raw.match(/^#\s+(.+)$/m);
      if (h1) title = h1[1].trim();
    }

    return { id, title, globs, keywords, content, source: filePath, autoGenerated };
  } catch {
    return null;
  }
}

/** Load all modular rules from .mochi/rules/ in cwd */
export function loadRules(projectRoot: string): ProjectRule[] {
  const rulesDir = resolve(projectRoot, '.mochi', 'rules');
  if (!existsSync(rulesDir)) return [];
  try {
    const files = readdirSync(rulesDir).filter((f) => f.endsWith('.md'));
    const rules: ProjectRule[] = [];
    for (const f of files) {
      const parsed = parseRuleFile(join(rulesDir, f));
      if (parsed) rules.push(parsed);
    }
    return rules;
  } catch {
    return [];
  }
}

/** Filter rules relevant to active file paths or prompt text */
export function selectActiveRules(
  rules: ProjectRule[],
  activeFiles: string[] = [],
  promptText = ''
): ProjectRule[] {
  if (rules.length === 0) return [];
  const textLower = promptText.toLowerCase();

  return rules.filter((r) => {
    // If no triggers specified, rule applies universally
    if ((!r.globs || r.globs.length === 0) && (!r.keywords || r.keywords.length === 0)) {
      return true;
    }

    // Match file extension/glob
    if (r.globs && r.globs.length > 0 && activeFiles.length > 0) {
      for (const g of r.globs) {
        const ext = g.startsWith('*') ? g.slice(1) : g;
        if (activeFiles.some((f) => f.endsWith(ext) || f.includes(ext))) return true;
      }
    }

    // Match keyword
    if (r.keywords && r.keywords.length > 0) {
      for (const kw of r.keywords) {
        if (textLower.includes(kw.toLowerCase())) return true;
      }
    }

    return false;
  });
}

/** Synthesize and save a new rule to .mochi/rules/ */
export function synthesizeRule(
  projectRoot: string,
  ruleName: string,
  title: string,
  content: string,
  opts: { globs?: string[]; keywords?: string[] } = {}
): void {
  const rulesDir = resolve(projectRoot, '.mochi', 'rules');
  if (!existsSync(rulesDir)) mkdirSync(rulesDir, { recursive: true });

  const safeName = ruleName.toLowerCase().replace(/[^a-z0-9_-]/g, '-');
  const filePath = join(rulesDir, `${safeName}.md`);
  const frontmatter = [
    '---',
    `title: "${title}"`,
    opts.globs && opts.globs.length > 0 ? `globs: ${JSON.stringify(opts.globs)}` : null,
    opts.keywords && opts.keywords.length > 0 ? `keywords: ${JSON.stringify(opts.keywords)}` : null,
    'autoGenerated: true',
    '---',
    '',
    content.trim(),
    '',
  ].filter(Boolean).join('\n');

  writeFileSync(filePath, frontmatter, 'utf8');
}
